FROM node as builder

WORKDIR /build

COPY package.json ./
RUN npm install

COPY . .

ARG node_env=production
ENV NODE_ENV ${node_env}

RUN npm run build web-app

FROM nginx:alpine

WORKDIR /dist

COPY --from=builder /build/dist/apps/web-app /usr/share/nginx/html

ARG port=80
ENV PORT ${port}
EXPOSE ${port}
