allowBuilds:
  '@firebase/util': true
  '@fortawesome/fontawesome-common-types': false
  '@fortawesome/fontawesome-svg-core': false
  '@fortawesome/free-solid-svg-icons': false
  '@parcel/watcher': false
  '@swc/core': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  protobufjs: false
  re2: false
  unrs-resolver: false
