name: Node.js Lint

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci --workspace libtwister
      - run: npm ci --workspace web-app
      - run: npm run --workspaces build
      - run: npm run --workspaces lint
