name: Node.js Lint

on:
  pull_request:
    branches: [master]

env:
  NODE_ENV: dev

jobs:
  lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run -w libtwister build
      - run: npm run -w libtwister lint

  app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run -w web-app build
      - run: npm run -w web-app lint
