# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Substitute Secrets into Tokenised File
        uses: Lambdaspire/action-substitute-secrets-in-file@main
        with:
          file: apps/web-app/src/environments/environment.ts
          tokenPattern: ${TOKEN}
          secretsJson: ${{ toJSON(secrets) }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build-version
      - run: npm run affected:build -- --base=origin/main
      - run: npm run affected:lint -- --base=origin/main
